### ISSUE TITLE
Problems for train.

### ISSUE THREAD

**Issue by qliu520** [qaz670756/LSNet#6]
When I try "python train.py", it appeared "torch.nn.modules.module.ModuleAttributeError: 'AdaptiveAvgPool2d' object has no attribute 'total_ops'". Is this a question of my torch version？

Our version：
Python 3.8.13
>>> torch.__version__
'1.7.1+cu101'
>>> torchvision.__version__
'0.8.2+cu101'

**Comment by qaz670756** [comment]
Hi, I think you should update the pytorch version, as for us, the torch version is 1.10.0
